/* * * * * * * * * * * * * * * * *
 *    CMST 495 6380 Group 2      *
 * * * * * * * * * * * * * * * * *
 *
 * Name: game.js
 * Author: Thuan Bui, Christopher Sankey, Nathan Woodson, Danny Ramirez
 * Description:
 *
 */


// Global variables

// DOM variables
const input = document.querySelector('#wordInput');
const word = document.querySelector('.word');

// Game state
let gameStarted = false;


/**
 * Validator Class
 * 
 * Description: Takes care of comparing the player's input
 * against the current word.
 */
class Validator {
  display;
  word;
  level;

  constructor(display) {
    this.display = display;
    this.level = 0;
    console.log('Validator ON!');
  }

  levelUp() {
    this.level++;
    this.display.displayLevel(this.level);
  }

  getLevel() {
    return this.level;
  }

  /**
   * Randomly selects a word from the array depending on the 
   * length of the array.
   * 
   * @return {String}
   */
  setWord(word) {
    console.log(word);
    this.word = word;
    this.display.displayWord(word);
  }

  /**
   * Compares the player's input against the 
   * word generated by setWord().
   * 
   * @return {Boolean}
   */
  checkWord(word) {
    if (this.word === word) {
      console.log('Match!');
      return true;
    } else {
      console.log('No match...');
      return false;
    }
  }
}